apiVersion: batch/v1
kind: Job
metadata:
  name: hp-tuning-jobs-10
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - args:
        - --n_estimators=100
        - --max_depth=5
        - --min_samples_split=5
        - --min_samples_leaf=1
        command:
        - python
        - house_price_prediction.py
        image: house-price-model:v1
        name: house-price-container
      restartPolicy: Never
