name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pip install pytest 
          pip show pytest  # Check if pytest is installed
          pytest tests/

  build_docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t house-price-model:$GITHUB_SHA .
          docker tag house-price-model:$GITHUB_SHA house-price-model:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_docker

    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Set Kubeconfig from Secret
        env:
          KUBECONFIG_B64: ${{ secrets.KUBECONFIG_B64 }}
        run: |
          mkdir -p $HOME/.kube  # Create the .kube directory
          echo "$KUBECONFIG_B64" | base64 --decode > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          kubectl config get-contexts  # Check available contexts

      - name: Set Kubectl Context
        run: |
          kubectl config use-context minikube  # Set to 'minikube' context

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/rf-inference rf-inference-container=house-price-model:$GITHUB_SHA
