name: CI/CD Pipeline for House Price Model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Step 1: Run Unit Tests
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pip install pytest
          pytest test_model.py

  # Step 2: Build and Push Docker Image
  build_docker:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/house-price-model:$GITHUB_SHA .
          docker tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/house-price-model:$GITHUB_SHA gcr.io/${{ secrets.GCP_PROJECT_ID }}/house-price-model:latest

      - name: Push Docker image to GCR
        run: |
          echo ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }} | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud --quiet auth configure-docker
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/house-price-model:$GITHUB_SHA

  # Step 3: Deploy to Google Cloud Run
  deploy_cloud_run:
    runs-on: ubuntu-latest
    needs: build_docker

    steps:
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy house-price-api \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/house-price-model:$GITHUB_SHA \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
