name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pip install pytest 
          pip show pytest  # Check if pytest is installed
          pytest tests/

  build_docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t house-price-model:$GITHUB_SHA .
          docker tag house-price-model:$GITHUB_SHA house-price-model:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_docker

    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Create Kubeconfig Directory
        run: mkdir -p $HOME/.kube

      - name: Write Certificates from Secrets
        run: |
          echo "${{ secrets.MINIKUBE_CA_CRT }}" > $HOME/.kube/ca.crt
          echo "${{ secrets.MINIKUBE_CLIENT_CRT }}" > $HOME/.kube/client.crt
          echo "${{ secrets.MINIKUBE_CLIENT_KEY }}" > $HOME/.kube/client.key

      - name: Create Kubeconfig
        run: |
          cat <<EOF > $HOME/.kube/config
          apiVersion: v1
          clusters:
          - cluster:
              certificate-authority: $HOME/.kube/ca.crt
              server: https://192.168.49.2:8443
            name: minikube
          contexts:
          - context:
              cluster: minikube
              namespace: default
              user: minikube
            name: minikube
          current-context: minikube
          kind: Config
          users:
          - name: minikube
            user:
              client-certificate: $HOME/.kube/client.crt
              client-key: $HOME/.kube/client.key
          EOF
        env:
          KUBECONFIG: $HOME/.kube/config

      - name: Set Kubectl Context
        run: kubectl config use-context minikube

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/rf-inference rf-inference-container=house-price-model:$GITHUB_SHA

  deploy_self_hosted:
    runs-on: self-hosted
    needs: build_docker

    steps:
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/rf-inference rf-inference-container=house-price-model:$GITHUB_SHA
